import type { Metadata } from "next";
import Link from "next/link";

import { getSupportEmail } from "@wildfires-org/turboplan-env";

import { LegalPage } from "@/components/legal/legal-page";
import { brand } from "@/lib/brand";
import { buildPageMetadata } from "@/lib/seo";
import { routing } from "@/utils/routing";

export const metadata: Metadata = buildPageMetadata({
  title: "Terms of Service",
  description: `The terms for using ${brand.name}: accounts, your content, AI-drafted documents, plans and billing, and acceptable use.`,
  path: routing.terms(),
});

export default function TermsPage() {
  const supportEmail = getSupportEmail();

  return (
    <LegalPage title="Terms of Service" updated="October 2, 2026">
      <p>
        These terms govern your use of {brand.name} (the &quot;Service&quot;).
        By creating an account or using the Service, you agree to them. If you
        use the Service for an organization, you agree on its behalf.
      </p>

      <h2>The Service</h2>
      <p>
        {brand.name} helps teams plan environmental review work: it researches
        precedent, tracks tasks and drafts documents such as scoping letters,
        categorical exclusion records and environmental assessments from the
        information you provide.
      </p>

      <h2>AI-drafted documents</h2>
      <p>
        Drafts, research and suggestions are generated by AI and can be
        incomplete or wrong. They are starting points for qualified people to
        review, not legal or professional advice. You are responsible for
        checking every document before you rely on it or submit it. Whether a
        document is sufficient is decided by the agency or official with
        authority over the review. The Service does not guarantee any outcome.
      </p>

      <h2>Accounts</h2>
      <p>
        Keep your sign-in email secure and tell us about any unauthorized use.
        Organization owners control who belongs to their organizations, offices
        and projects, and what each member can do.
      </p>

      <h2>Your content</h2>
      <p>
        You keep all rights to the content you upload or create. You give us
        permission to host, process and display it only as needed to run the
        Service for you, including sending it to the providers listed in our{" "}
        <Link href={routing.privacy()}>Privacy Policy</Link>. If you make a
        project public, anyone can view it in the public catalog. Only upload
        content you have the right to share.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Don&apos;t break the law or infringe anyone&apos;s rights.</li>
        <li>
          Don&apos;t try to access accounts, projects or data that aren&apos;t
          yours.
        </li>
        <li>
          Don&apos;t disrupt the Service, probe it for vulnerabilities without
          permission, or scrape or resell it.
        </li>
        <li>
          Don&apos;t upload malware or content you know to be false or
          misleading.
        </li>
      </ul>

      <h2>Plans and billing</h2>
      <p>
        Paid plans are billed monthly in advance through Stripe, at the prices
        shown on our <Link href={routing.pricing()}>pricing page</Link>, plus
        any additional seats. Each plan includes a monthly amount of usage
        credits. You can cancel at any time, and your plan stays active until
        the end of the period you paid for. Except where the law requires
        otherwise, fees are not refundable. We will tell you before any price
        change applies to your subscription.
      </p>

      <h2>Suspension and termination</h2>
      <p>
        You can stop using the Service and delete your account at any time. We
        may suspend or end access for a breach of these terms, for non-payment,
        or to protect the Service or other users.
      </p>

      <h2>Disclaimers and limitation of liability</h2>
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available&quot;,
        without warranties of any kind, to the extent the law allows. To the
        extent the law allows, we are not liable for indirect, incidental or
        consequential damages, or for lost profits or data. Our total liability
        for any claim is limited to the amount you paid us in the 12 months
        before the claim.
      </p>

      <h2>Changes</h2>
      <p>
        When these terms change, we update this page and the date at the top. If
        you keep using the Service after a change takes effect, you accept the
        updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a href={`mailto:${supportEmail}`}>{supportEmail}</a>.
      </p>
    </LegalPage>
  );
}
