/**
 * Documents an anonymous visitor attaches to the landing-page prompt, shared
 * by the landing page (picker), the web app (signup handoff) and the server
 * (presign and claim). Client-safe: nothing here touches storage.
 */

/** Most documents a visitor can attach to the landing-page prompt. */
export const MAX_LANDING_UPLOADS = 5;

/**
 * Query param carrying the staging keys on the landing page -> /self-service
 * handoff URL, one param per key. Contract between both apps — do not rename.
 */
export const LANDING_UPLOADS_PARAM = "landingUploads";

/**
 * Staging prefix for landing-page attachments, before any account exists.
 * `claimLandingUpload` moves an object from here into its new owner's
 * `uploads/{userId}/` once the project is created; anything never claimed is
 * removed by the bucket lifecycle rule (see `scripts/deploy-api.sh`).
 */
export const LANDING_UPLOAD_PREFIX = "landing-uploads";

/**
 * The key segment becomes `project_document.filename` (varchar 255), and
 * `uniqueStorageName` prepends `{13-digit timestamp}-{36-char UUID}-`.
 */
const MAX_LANDING_SEGMENT_LENGTH = 255;
const STORAGE_NAME_PREFIX_LENGTH = 51;
export const LANDING_FILENAME_MAX_LENGTH =
  MAX_LANDING_SEGMENT_LENGTH - STORAGE_NAME_PREFIX_LENGTH;

// Exactly the segment `uniqueStorageName` produces from a sanitized landing
// filename, capturing the filename. No separators, dot-segments, URL
// delimiters, control/format characters, line/paragraph separators or lone
// surrogates can appear in it.
const LANDING_SEGMENT_PATTERN =
  /^\d{13}-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}-([^/\\?#%\p{Cc}\p{Cf}\p{Cs}\p{Zl}\p{Zp}]+)$/u;

export type LandingUploadKey = {
  /** The single key segment below the staging prefix */
  segment: string;
  /** The visitor's (sanitized) filename, without the unique prefix */
  originalFilename: string;
};

/**
 * Parse a client-supplied staging key, or return null unless it is exactly
 * `landing-uploads/<segment generated by the landing presign>`. The key comes
 * from an anonymous browser, so anything else — traversal, extra separators,
 * another prefix — is refused before storage is touched.
 */
export const parseLandingUploadKey = (
  key: unknown,
): LandingUploadKey | null => {
  if (typeof key !== "string") {
    return null;
  }

  const prefix = `${LANDING_UPLOAD_PREFIX}/`;
  if (!key.startsWith(prefix)) {
    return null;
  }

  const segment = key.slice(prefix.length);
  if (segment.length > MAX_LANDING_SEGMENT_LENGTH) {
    return null;
  }

  const match = LANDING_SEGMENT_PATTERN.exec(segment);
  if (!match) {
    return null;
  }

  return { segment, originalFilename: match[1] };
};
