import { type LoaderPlugin, loader } from "fumadocs-core/source";

import { docs } from "@/.source";
import { brand } from "@/lib/brand";
import { rebrandDocsText } from "@/lib/docs-branding";

// Page titles and descriptions drive the sidebar, <title>, social cards and
// search, so they get the same rebranding as the prose (see docs-branding).
// Mutated in place: page data carries a lazy `content` getter that a spread
// would trigger.
const rebrandFrontmatter: LoaderPlugin = {
  transformStorage: ({ storage }) => {
    for (const path of storage.getFiles()) {
      const file = storage.read(path);
      if (file?.format !== "page") {
        continue;
      }

      const { data } = file;
      if (data.title) {
        data.title = rebrandDocsText(data.title, brand.name);
      }
      if (data.description) {
        data.description = rebrandDocsText(data.description, brand.name);
      }
    }
  },
};

// Page tree + page lookup for the /docs route. `docs` is generated by
// fumadocs-mdx into the root `.source/` dir from `content/docs`.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
  plugins: [rebrandFrontmatter],
});
