import {
  isProjectDocumentMimeType,
  normalizeContentType,
  PROJECT_DOCUMENT_MAX_FILE_SIZE,
  type ProjectDocumentMimeType,
  UploadError,
  UploadErrorCode,
} from "../types";
import {
  canonicalStorageKey,
  copyStorageObject,
  deleteStorageObject,
  getPublicUrl,
  headStorageObject,
  isSafeKeySegment,
} from "./r2-client";

/**
 * Staging prefix for documents an anonymous visitor attaches on the landing
 * page, before any account exists. `claimLandingUpload` moves an object from
 * here into its new owner's `uploads/{userId}/` once the project is created;
 * anything never claimed is an orphan for the bucket lifecycle rule.
 */
export const LANDING_UPLOAD_PREFIX = "landing-uploads";

/**
 * Stripped from a landing filename on top of `sanitizeFilename`: `#` and `%`
 * do not survive the object's public URL (fragment / percent-decoding), and
 * Unicode control and format characters (e.g. RTLO) can spoof the shown name.
 */
export const LANDING_FILENAME_STRIP_CHARS = /[#%\p{Cc}\p{Cf}]/gu;

/**
 * The key segment becomes `project_document.filename` (varchar 255), and
 * `uniqueStorageName` prepends `{13-digit timestamp}-{36-char UUID}-`.
 */
const MAX_LANDING_SEGMENT_LENGTH = 255;
const STORAGE_NAME_PREFIX_LENGTH = 51;
export const LANDING_FILENAME_MAX_LENGTH =
  MAX_LANDING_SEGMENT_LENGTH - STORAGE_NAME_PREFIX_LENGTH;

// Exactly the segment `uniqueStorageName` produces from a sanitized landing
// filename, capturing the filename. No separators, dot-segments, URL
// delimiters or control/format characters can appear in it.
const LANDING_SEGMENT_PATTERN =
  /^\d{13}-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}-([^/\\?#%\p{Cc}\p{Cf}]+)$/u;

export type LandingUploadKey = {
  /** The single key segment below the staging prefix */
  segment: string;
  /** The visitor's (sanitized) filename, without the unique prefix */
  originalFilename: string;
};

/**
 * Parse a client-supplied staging key, or return null unless it is exactly
 * `landing-uploads/<segment generated by the landing presign>`. The key comes
 * from an anonymous browser, so anything else — traversal, extra separators,
 * another prefix — is refused before storage is touched.
 */
export const parseLandingUploadKey = (
  key: unknown,
): LandingUploadKey | null => {
  if (typeof key !== "string") {
    return null;
  }

  const prefix = `${LANDING_UPLOAD_PREFIX}/`;
  if (!key.startsWith(prefix)) {
    return null;
  }

  const segment = key.slice(prefix.length);
  if (segment.length > MAX_LANDING_SEGMENT_LENGTH) {
    return null;
  }

  const match = LANDING_SEGMENT_PATTERN.exec(segment);
  if (!match) {
    return null;
  }

  return { segment, originalFilename: match[1] };
};

export type ClaimedLandingUpload = {
  /** Public URL of the object at its new key */
  url: string;
  /** New key, under `uploads/{userId}/` */
  key: string;
  /** Size reported by storage */
  size: number;
  /** Content type reported by storage */
  contentType: ProjectDocumentMimeType;
  originalFilename: string;
};

/**
 * Move a landing-page staging upload into `userId`'s own upload prefix, so it
 * can be registered as a project document like any upload of theirs.
 *
 * Type and size come from storage (HEAD), never from the client, and are
 * re-checked against the project document rules. The copy is pinned to the
 * inspected ETag. The staging object is then deleted best-effort.
 *
 * Returns null when no object exists at `key` (expired, already claimed).
 * Throws an `UploadError` for a malformed key or a disallowed object, and
 * passes storage errors through.
 */
export const claimLandingUpload = async (
  key: string,
  userId: string,
): Promise<ClaimedLandingUpload | null> => {
  const parsed = parseLandingUploadKey(key);
  if (!parsed) {
    throw new UploadError(
      "Invalid landing upload key",
      UploadErrorCode.VALIDATION_ERROR,
      { key },
    );
  }

  if (!isSafeKeySegment(userId)) {
    throw new UploadError(
      "Invalid upload owner",
      UploadErrorCode.VALIDATION_ERROR,
    );
  }

  const destinationKey = `uploads/${userId}/${parsed.segment}`;
  const url = getPublicUrl(destinationKey);

  // The registered URL must resolve back to this exact key, or ownership
  // checks and deletes would later act on a different object.
  if (canonicalStorageKey(url) !== destinationKey) {
    throw new UploadError(
      "Landing upload key does not map to a storage URL",
      UploadErrorCode.VALIDATION_ERROR,
      { key },
    );
  }

  const object = await headStorageObject(key);
  if (!object) {
    return null;
  }

  const contentType = normalizeContentType(object.contentType);
  if (!isProjectDocumentMimeType(contentType)) {
    throw new UploadError(
      "Unsupported file type",
      UploadErrorCode.VALIDATION_ERROR,
      { key, contentType: object.contentType },
    );
  }

  if (object.size <= 0 || object.size > PROJECT_DOCUMENT_MAX_FILE_SIZE) {
    throw new UploadError(
      `File size ${object.size} is outside the allowed range`,
      UploadErrorCode.VALIDATION_ERROR,
      { key, size: object.size, maxSize: PROJECT_DOCUMENT_MAX_FILE_SIZE },
    );
  }

  await copyStorageObject(key, destinationKey, object.etag);

  try {
    await deleteStorageObject(key);
  } catch (error) {
    // The copy is what matters; a leftover staging object expires on its own.
    console.warn("Failed to delete claimed landing upload:", key, error);
  }

  return {
    url,
    key: destinationKey,
    size: object.size,
    contentType,
    originalFilename: parsed.originalFilename,
  };
};
